import { Hotel } from "./types";

export const HOTELS: Hotel[] = [
  {
    id: "h1",
    name: "Chao Phraya Riverside",
    location: "Bangkok",
    thumbnail: "https://picsum.photos/seed/h1/600/400",
    rating: 4.6,
    roomTypes: [
      { code: "standard", label: "Standard", baseRatePerNight: 1200 },
      { code: "deluxe",   label: "Deluxe",   baseRatePerNight: 1800 },
      { code: "suite",    label: "Suite",    baseRatePerNight: 2700 },
    ],
  },
  {
    id: "h2",
    name: "Old Town Boutique",
    location: "Chiang Mai",
    thumbnail: "https://picsum.photos/seed/h2/600/400",
    rating: 4.4,
    roomTypes: [
      { code: "standard", label: "Standard", baseRatePerNight: 900 },
      { code: "deluxe",   label: "Deluxe",   baseRatePerNight: 1500 },
      { code: "suite",    label: "Suite",    baseRatePerNight: 2200 },
    ],
  },
  {
    id: "h3",
    name: "Andaman Beachfront",
    location: "Phuket",
    thumbnail: "https://picsum.photos/seed/h3/600/400",
    rating: 4.8,
    roomTypes: [
      { code: "standard", label: "Standard", baseRatePerNight: 1600 },
      { code: "deluxe",   label: "Deluxe",   baseRatePerNight: 2200 },
      { code: "suite",    label: "Suite",    baseRatePerNight: 3500 },
    ],
  },
  {
    id: "h4",
    name: "Sukhumvit Skylight",
    location: "Bangkok",
    thumbnail: "https://picsum.photos/seed/h4/600/400",
    rating: 4.7,
    roomTypes: [
      { code: "standard", label: "Standard", baseRatePerNight: 1100 },
      { code: "deluxe",   label: "Deluxe",   baseRatePerNight: 1700 },
      { code: "suite",    label: "Suite",    baseRatePerNight: 2600 },
    ],
  },
  {
    id: "h5",
    name: "Patong Beach Resort",
    location: "Phuket",
    thumbnail: "https://picsum.photos/seed/h5/600/400",
    rating: 4.3,
    roomTypes: [
      { code: "standard", label: "Standard", baseRatePerNight: 1400 },
      { code: "deluxe",   label: "Deluxe",   baseRatePerNight: 2000 },
      { code: "suite",    label: "Suite",    baseRatePerNight: 3000 },
    ],
  },
  {
    id: "h6",
    name: "Kata Hills Panoramic",
    location: "Phuket",
    thumbnail: "https://picsum.photos/seed/h6/600/400",
    rating: 4.9,
    roomTypes: [
      { code: "standard", label: "Standard", baseRatePerNight: 1700 },
      { code: "deluxe",   label: "Deluxe",   baseRatePerNight: 2300 },
      { code: "suite",    label: "Suite",    baseRatePerNight: 3600 },
    ],
  },
  {
    id: "h7",
    name: "Nimman Creative Suites",
    location: "Chiang Mai",
    thumbnail: "https://picsum.photos/seed/h7/600/400",
    rating: 4.5,
    roomTypes: [
      { code: "standard", label: "Standard", baseRatePerNight: 950 },
      { code: "deluxe",   label: "Deluxe",   baseRatePerNight: 1400 },
      { code: "suite",    label: "Suite",    baseRatePerNight: 2100 },
    ],
  },
  {
    id: "h8",
    name: "Pattaya Bay Walk",
    location: "Pattaya",
    thumbnail: "https://picsum.photos/seed/h8/600/400",
    rating: 4.2,
    roomTypes: [
      { code: "standard", label: "Standard", baseRatePerNight: 900 },
      { code: "deluxe",   label: "Deluxe",   baseRatePerNight: 1350 },
      { code: "suite",    label: "Suite",    baseRatePerNight: 2000 },
    ],
  },
  {
    id: "h9",
    name: "Railay Cliff Villas",
    location: "Krabi",
    thumbnail: "https://picsum.photos/seed/h9/600/400",
    rating: 4.7,
    roomTypes: [
      { code: "standard", label: "Standard", baseRatePerNight: 1600 },
      { code: "deluxe",   label: "Deluxe",   baseRatePerNight: 2300 },
      { code: "suite",    label: "Suite",    baseRatePerNight: 3200 },
    ],
  },
  {
    id: "h10",
    name: "Hua Hin Colonial Retreat",
    location: "Hua Hin",
    thumbnail: "https://picsum.photos/seed/h10/600/400",
    rating: 4.1,
    roomTypes: [
      { code: "standard", label: "Standard", baseRatePerNight: 1100 },
      { code: "deluxe",   label: "Deluxe",   baseRatePerNight: 1600 },
      { code: "suite",    label: "Suite",    baseRatePerNight: 2400 },
    ],
  },
  {
    id: "h11",
    name: "Samui Coconut Grove",
    location: "Koh Samui",
    thumbnail: "https://picsum.photos/seed/h11/600/400",
    rating: 4.6,
    roomTypes: [
      { code: "standard", label: "Standard", baseRatePerNight: 1400 },
      { code: "deluxe",   label: "Deluxe",   baseRatePerNight: 2000 },
      { code: "suite",    label: "Suite",    baseRatePerNight: 3100 },
    ],
  },
  {
    id: "h12",
    name: "Golden Triangle Lodge",
    location: "Chiang Rai",
    thumbnail: "https://picsum.photos/seed/h12/600/400",
    rating: 4.3,
    roomTypes: [
      { code: "standard", label: "Standard", baseRatePerNight: 800 },
      { code: "deluxe",   label: "Deluxe",   baseRatePerNight: 1200 },
      { code: "suite",    label: "Suite",    baseRatePerNight: 1900 },
    ],
  },
  {
    id: "h13",
    name: "Ayutthaya River Heritage",
    location: "Ayutthaya",
    thumbnail: "https://picsum.photos/seed/h13/600/400",
    rating: 4.0,
    roomTypes: [
      { code: "standard", label: "Standard", baseRatePerNight: 900 },
      { code: "deluxe",   label: "Deluxe",   baseRatePerNight: 1300 },
      { code: "suite",    label: "Suite",    baseRatePerNight: 2000 },
    ],
  },
  {
    id: "h14",
    name: "Bang Saen Breeze",
    location: "Bang Saen",
    thumbnail: "https://picsum.photos/seed/h14/600/400",
    rating: 4.1,
    roomTypes: [
      { code: "standard", label: "Standard", baseRatePerNight: 850 },
      { code: "deluxe",   label: "Deluxe",   baseRatePerNight: 1200 },
      { code: "suite",    label: "Suite",    baseRatePerNight: 1800 },
    ],
  },
  {
    id: "h15",
    name: "River Kwai Retreat",
    location: "Kanchanaburi",
    thumbnail: "https://picsum.photos/seed/h15/600/400",
    rating: 4.4,
    roomTypes: [
      { code: "standard", label: "Standard", baseRatePerNight: 1000 },
      { code: "deluxe",   label: "Deluxe",   baseRatePerNight: 1500 },
      { code: "suite",    label: "Suite",    baseRatePerNight: 2300 },
    ],
  },
  {
    id: "h16",
    name: "Koh Chang Serenity",
    location: "Koh Chang",
    thumbnail: "https://picsum.photos/seed/h16/600/400",
    rating: 4.2,
    roomTypes: [
      { code: "standard", label: "Standard", baseRatePerNight: 1100 },
      { code: "deluxe",   label: "Deluxe",   baseRatePerNight: 1600 },
      { code: "suite",    label: "Suite",    baseRatePerNight: 2400 },
    ],
  },
  {
    id: "h17",
    name: "Pai Mountain Lodge",
    location: "Pai",
    thumbnail: "https://picsum.photos/seed/h17/600/400",
    rating: 4.3,
    roomTypes: [
      { code: "standard", label: "Standard", baseRatePerNight: 700 },
      { code: "deluxe",   label: "Deluxe",   baseRatePerNight: 1100 },
      { code: "suite",    label: "Suite",    baseRatePerNight: 1600 },
    ],
  },
  {
    id: "h18",
    name: "Trang Emerald Coast",
    location: "Trang",
    thumbnail: "https://picsum.photos/seed/h18/600/400",
    rating: 4.2,
    roomTypes: [
      { code: "standard", label: "Standard", baseRatePerNight: 950 },
      { code: "deluxe",   label: "Deluxe",   baseRatePerNight: 1400 },
      { code: "suite",    label: "Suite",    baseRatePerNight: 2100 },
    ],
  },
  {
    id: "h19",
    name: "Udon Thani Central",
    location: "Udon Thani",
    thumbnail: "https://picsum.photos/seed/h19/600/400",
    rating: 3.9,
    roomTypes: [
      { code: "standard", label: "Standard", baseRatePerNight: 750 },
      { code: "deluxe",   label: "Deluxe",   baseRatePerNight: 1100 },
      { code: "suite",    label: "Suite",    baseRatePerNight: 1600 },
    ],
  },
  {
    id: "h20",
    name: "Sukhothai Ancient Park Stay",
    location: "Sukhothai",
    thumbnail: "https://picsum.photos/seed/h20/600/400",
    rating: 4.1,
    roomTypes: [
      { code: "standard", label: "Standard", baseRatePerNight: 800 },
      { code: "deluxe",   label: "Deluxe",   baseRatePerNight: 1200 },
      { code: "suite",    label: "Suite",    baseRatePerNight: 1800 },
    ],
  },
  {
    id: "h21",
    name: "Phang Nga Bay Resort",
    location: "Phang Nga",
    thumbnail: "https://picsum.photos/seed/h21/600/400",
    rating: 4.6,
    roomTypes: [
      { code: "standard", label: "Standard", baseRatePerNight: 1500 },
      { code: "deluxe",   label: "Deluxe",   baseRatePerNight: 2100 },
      { code: "suite",    label: "Suite",    baseRatePerNight: 3000 },
    ],
  },
  {
    id: "h22",
    name: "Surat Thani Riverside",
    location: "Surat Thani",
    thumbnail: "https://picsum.photos/seed/h22/600/400",
    rating: 4.0,
    roomTypes: [
      { code: "standard", label: "Standard", baseRatePerNight: 850 },
      { code: "deluxe",   label: "Deluxe",   baseRatePerNight: 1300 },
      { code: "suite",    label: "Suite",    baseRatePerNight: 1900 },
    ],
  },
  {
    id: "h23",
    name: "Bangkok Airport Transit",
    location: "Bangkok",
    thumbnail: "https://picsum.photos/seed/h23/600/400",
    rating: 3.8,
    roomTypes: [
      { code: "standard", label: "Standard", baseRatePerNight: 800 },
      { code: "deluxe",   label: "Deluxe",   baseRatePerNight: 1200 },
      { code: "suite",    label: "Suite",    baseRatePerNight: 1700 },
    ],
  },
  {
    id: "h24",
    name: "Koh Lanta Coral Bay",
    location: "Krabi",
    thumbnail: "https://picsum.photos/seed/h24/600/400",
    rating: 4.5,
    roomTypes: [
      { code: "standard", label: "Standard", baseRatePerNight: 1300 },
      { code: "deluxe",   label: "Deluxe",   baseRatePerNight: 1900 },
      { code: "suite",    label: "Suite",    baseRatePerNight: 2800 },
    ],
  },
];
